Sprint_2
chris-lebedeva/qa_python pull request #2
Opened 2023-05-10 18:47 UTC by chris-lebedeva

Added 12 unit tests

2023-05-10 19:08 UTC, kadirovgm requested changes

2023-05-10 19:08 UTC, kadirovgm commented on .gitignore
> +
Можно лучше: в файле гитигнора мы должны хранить только те локальные файлы, которых не хотим запушить в общий репозиторий, в твоем случае ты используешь шаблон, где много излишней информации не касающихся нашего проекта

2023-05-10 19:08 UTC, kadirovgm commented on tests.py
> +        assert collector.books_rating['Илиада'] == 1
Нужно исправить: для этого у нас есть метод `get_book_rating`, стоит воспользоваться ею

2023-05-10 19:08 UTC, kadirovgm commented on tests.py
> +        collector.set_book_rating('Му-му', 1)
Нужно исправить: по умолчанию и так выставится "1" по заданию, так что скорее здесь нужно проверить, что при выставлении оценки менее 1, рейтинг книги будет равен 1

2023-05-10 19:08 UTC, kadirovgm commented on tests.py
> +        assert collector.books_rating['Му-му'] >= 1
Нужно исправить: для этого у нас есть метод `get_book_rating`, стоит воспользоваться ею

2023-05-10 19:08 UTC, kadirovgm commented on tests.py
> +        assert collector.books_rating['Улисс'] <= 10
Нужно исправить: для этого у нас есть метод `get_book_rating`, стоит воспользоваться ею

2023-05-10 19:08 UTC, kadirovgm commented on tests.py
> +        collector.set_book_rating('Улисс', 10)
Нужно исправить: тебе нужно взять значение, выходящее за рамки граничных значений и убедиться, что при этом рейтинг равен 1 (значение по умолчанию)

2023-05-10 19:08 UTC, kadirovgm commented on tests.py
> +        assert collector.get_books_with_specific_rating(8)
Нужно исправить: ты здесь просто выводишь список книг, надо проверить, что в списке содержится именно книга с рейтингом 8 (подсказка оператор `in`)

2023-05-10 19:08 UTC, kadirovgm commented on tests.py
> +        assert collector.get_books_rating()
Ты здесь просто выводишь словарь `get_books_rating`,  надо проверить, что добавленные книги в нем содержатся

2023-05-10 19:08 UTC, kadirovgm commented on tests.py
> +        collector.add_new_book('Сто лет одиночества')
Можно лучше: для unit теста достаточно, что хотя бы одна книга добавилась

2023-05-10 19:08 UTC, kadirovgm commented on tests.py
> +        assert collector.favorites[0]
Нужно исправить: некорректная проверка, тебе надо чекнуть, что книга добавилась в список favorites, здесь ты просто выводишь первый элемент списка, и тест проходит, так как он есть, но ты не гарантируешь, что там именно та книга, которую ты добавил

2023-05-10 19:08 UTC, kadirovgm commented on tests.py
> +        assert collector.get_list_of_favorites_books()
Нужно исправить: не просто выведи, а убедись, что в списке именно те книги, которых ты добавил

2023-05-12 15:11 UTC, kadirovgm requested changes

2023-05-12 15:11 UTC, kadirovgm commented on tests.py
> +        assert collector.get_book_rating('Илиада')
нужно исправить: тебе нужно все таки оставить проверку того, что рейтинг книги равен 1

2023-05-12 15:11 UTC, kadirovgm commented on tests.py
> +        assert collector.get_book_rating('Му-му')
Нужно исправить: тебе нужно проверить, что рейтинг книги равен 1

2023-05-12 15:11 UTC, kadirovgm commented on tests.py
> +        assert collector.get_book_rating('Улисс')
Нужно исправить: тебе нужно проверить, что рейтинг книги равен 1

2023-05-12 15:11 UTC, kadirovgm commented on tests.py
> +        if 8 in collector.books_rating.values():
Нужно исправить: слишком усложнила сделай проверку того, что книга Хитроумный идальго Дон Кихот Ламанчский в выводе списка get_books_with_specific_rating

assert "Хитроумный идальго Дон Кихот Ламанчский" == collector.get_books_with_specific_rating(8)

2023-05-12 15:11 UTC, kadirovgm commented on tests.py
> +        assert 'Улитка на склоне' in collector.favorites
Отлично!

2023-05-12 18:54 UTC, chris-lebedeva commented on tests.py
> +        if 8 in collector.books_rating.values():
Пришлось добавить индекс, поскольку возвращается именно список.
assert collector.get_books_with_specific_rating(8)[0] == 'Хитроумный идальго Дон Кихот Ламанчский'
Надеюсь, нормально :)

2023-05-12 22:59 UTC, kadirovgm approved these changes

2023-05-13 18:26 UTC, merged